name: oat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic-network::rampart=1.2.0
  - snakemake-minimal=7.2.1
  - bedtools
  - bcftools>=1.14
  - jq=1.6
  - samtools>=1.14
  - python=3.9
  - longshot=0.4.5
  - minimap2=2.24
  - artic-porechop=0.3.2pre
  - pip=23.0.1
  - imagemagick=7.1.0_27
  - nanoq=0.8.6
  - singularity=3.7.1
