name: oat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic-network::rampart=1.2.0
  - snakemake-minimal=7.2.1
  - bcftools=1.14
  - samtools=1.14
  - python=3.9
  - mamba=0.22.1
  - minimap2=2.24
  - artic-porechop=0.3.2pre
  - longshot=0.4.1
  - pip
  - imagemagick=7.1.0_27
  - nanoq=0.8.6
  - pip:
    - colorlog==6.6.0
    - biopython>=1.78
    - pandas==1.4.1
    - psutil==5.9.0
    - pygraphviz==1.9
    - pygments==2.11.2
    - GPUtil==1.4.0
